export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY";
export const GET_ALL_BRANDS = "GET_ALL_BRANDS";
export const CREATE_SUB_CATEGORY = "CREATE_SUB_CATEGORY";
export const GET_SUB_CATEGORY = "GET_SUB_CATEGORY";
export const GET_DETAILS_CATEGORY = "GET_DETAILS_CATEGORY";
export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const GET_PRODUCTS_DETAILS = "GET_PRODUCTS_DETAILS";
export const GET_PRODUCTS_LIKE = "GET_PRODUCTS_LIKE";
export const CREATE_PRODUCTS = "CREATE_PRODUCTS";
export const DELETE_PRODUCTS = "DELETE_PRODUCTS";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";

export const GET_ERROR = "GET_ERROR";